basePath: /
definitions:
  dto.CreatePackageResponse:
    properties:
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      message:
        example: Package created successfully
        type: string
    type: object
  dto.HealthCheckResponse:
    description: Resposta simples de status da API
    properties:
      message:
        example: OK!
        type: string
    type: object
  dto.HireCarrierRequest:
    description: Dados necessários para contratar uma transportadora
    properties:
      carrier_id:
        example: nebulix
        type: string
      package_id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
    required:
    - carrier_id
    - package_id
    type: object
  dto.PackageRequest:
    description: Dados necessários para criar um novo pacote
    properties:
      estado_destino:
        example: PR
        type: string
      peso_kg:
        example: 0.6
        maximum: 1000
        type: number
      produto:
        example: Camisa tamanho G
        maxLength: 100
        minLength: 2
        type: string
    required:
    - estado_destino
    - peso_kg
    - produto
    type: object
  dto.PackageResponse:
    description: Resposta com os dados de um pacote
    properties:
      entrega:
        $ref: '#/definitions/dto.ShippingQuoteResponse'
      estado_destino:
        example: PR
        type: string
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      peso_kg:
        example: 0.6
        type: number
      produto:
        example: Camisa tamanho G
        type: string
      regiao_destino:
        example: sul
        type: string
      status:
        example: criado
        type: string
    type: object
  dto.ShippingQuoteResponse:
    description: Dados de uma cotação de frete
    properties:
      prazo_estimado_dias:
        example: 4
        type: integer
      preco_estimado:
        example: 42.5
        type: number
      transportadora:
        example: Nebulix Logística
        type: string
      transportadora_id:
        example: nebulix
        type: string
    type: object
  dto.SuccessResponse:
    properties:
      message:
        example: Operation completed successfully
        type: string
    type: object
  dto.UpdateStatusRequest:
    description: Dados necessários para atualizar o status de um pacote
    properties:
      package_id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      status:
        example: enviado
        type: string
    required:
    - package_id
    - status
    type: object
host: localhost:5000
info:
  contact: {}
  description: API para gerenciamento de envios de pacotes por diferentes transportadoras
  title: Delivery Manager API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Verifica se a API está funcionando corretamente
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.HealthCheckResponse'
      summary: Health check da API
      tags:
      - health
  /package/:
    post:
      consumes:
      - application/json
      description: Cria um novo pacote com produto, peso e estado de destino. O sistema
        automaticamente mapeia o estado para a região correspondente e calcula as
        transportadoras disponíveis.
      parameters:
      - description: Dados do pacote
        in: body
        name: package
        required: true
        schema:
          $ref: '#/definitions/dto.PackageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Pacote criado com sucesso
          schema:
            $ref: '#/definitions/dto.CreatePackageResponse'
      summary: Criar um novo pacote
      tags:
      - packages
  /package/{id}:
    get:
      consumes:
      - application/json
      description: Retorna os dados completos de um pacote pelo ID, incluindo informações
        de entrega se uma transportadora foi contratada.
      parameters:
      - description: ID único do pacote
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Dados do pacote
          schema:
            $ref: '#/definitions/dto.PackageResponse'
      summary: Consultar um pacote específico
      tags:
      - packages
  /package/{id}/quote:
    post:
      consumes:
      - application/json
      description: Retorna cotações de frete disponíveis para um pacote, ordenadas
        por prazo de entrega. Inclui preços e prazos estimados de todas as transportadoras
        que atendem a região do pacote.
      parameters:
      - description: ID do pacote
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Cotações de frete disponíveis
          schema:
            items:
              $ref: '#/definitions/dto.ShippingQuoteResponse'
            type: array
      summary: Cotação de fretes
      tags:
      - packages
  /package/hire-carrier:
    post:
      consumes:
      - application/json
      description: 'Contrata uma transportadora para realizar a entrega do pacote.
        O status do pacote será automaticamente alterado para ''esperando_coleta''.
        Transportadoras disponíveis: nebulix, rotafacil, moventra.'
      parameters:
      - description: Dados para contratação
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.HireCarrierRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Transportadora contratada com sucesso
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
      summary: Contratar transportadora
      tags:
      - packages
  /package/status:
    put:
      consumes:
      - application/json
      description: 'Atualiza o status de um pacote específico. Status válidos: criado,
        esperando_coleta, coletado, enviado, entregue, extraviado.'
      parameters:
      - description: Dados para atualização de status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Status atualizado com sucesso
          schema:
            $ref: '#/definitions/dto.SuccessResponse'
      summary: Atualizar status de um pacote
      tags:
      - packages
swagger: "2.0"
